apiVersion: v1
kind: Service
metadata:
  name: {{ include "ray-cluster.fullname" . }}-svc
spec:
  ports:
    - name: ray-client
      protocol: TCP
      port: 10001
      targetPort: 10001
    - name: dashboard
      protocol: TCP
      port: 8265
      targetPort: 8265
  selector:
    ray.io/identifier: {{ include "ray-cluster.fullname" . }}-head
  type: ClusterIP
